[package]
name = "program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.18.7"

[dev-dependencies]
solana-program-test = "1.18.7"
solana-sdk = "1.18.7"

[lib]
crate-type = ["cdylib", "lib"]
